### ISSUE TITLE
FATAL  Invalid selection: Too many roles match selected values.

### ISSUE THREAD

**Issue by pulberg** [synfinatic/aws-sso-cli#298]
**Output of `aws-sso version`:**
```
➜ aws-sso version
AWS SSO CLI Version 1.7.4 -- Copyright 2021-2022 Aaron Turner
465eaafbcb29ea217e587a592ec5692937a3f176 (Homebrew) built at 2022-03-07T16:11:43+0000
```

**Describe the bug:**
Cannot select AccountAlias, AccountID, Email, or Role

**To Reproduce:**
 1. aws-sso exec
 2. try to select any option
 3. get error - FATAL   Invalid selection: Too many roles match selected values.

**Expected behavior:**
I am able to select from one of the available options

**Desktop (please complete the following information):**
 - OS: [e.g. macOS] macOS
 - Version [e.g. 10.15.5] 12.2.1

**Additional context:**

**Contents of `~/.aws-sso/config.yaml`:**
```
SSOConfig:
  Default:
    SSORegion: us-east-2
    StartUrl: https://xxxxxxx.awsapps.com/start
    DefaultRegion: us-east-2
DefaultSSO: Default
UrlAction: open
LogLevel: debug
HistoryLimit: 100
HistoryMinutes: 1440
```

**Comment by pulberg** [comment]
`aws-sso exec` --> `space` --> `enter`

shows `AccountAlias`, etc

I arrow-down to pick `AccountAlias`, then click `enter` and get the error

**Comment by synfinatic** [comment]
\<Enter\> selects the role to assume.    You can type or use the arrow keys to select the unique set of tags which correspond to a single role.  If you ever hit \<Enter\> before you have a single role shown it will generate that error.  So it would be:

Down Arrow to highlight `AccountAlias` and then hit `<space>` to select it by moving to the next word in the key/value pair.

**Comment by pulberg** [comment]
Ah, I see, a bit different than other tools, thanks for the guidance. I think i did it right, but i get an sso error - 

```
➜ aws-sso exec
Please use `exit` or `Ctrl-D` to quit.
> AccountAlias my-account-alias arn:aws:iam::1234567890:role/myaccountrole
DEBUG   Will not override current AWS_DEFAULT_REGION=us-east-2
DEBUG   Getting role credentials for arn:aws:iam::1234567890:role/myaccountrole
DEBUG   Fetching STS token from AWS SSO
DEBUG   Getting 1234567890:myaccountrole directly
FATAL   Unable to get role credentials for arn:aws:iam::1234567890:role/myaccountrole  error="operation error SSO: GetRoleCredentials, https response error StatusCode: 401, RequestID: , UnauthorizedException: Session token not found or invalid"
```

**Comment by pulberg** [comment]
No, i changed all of that data for the purpose of the post, i can't post the actual data.

**Comment by synfinatic** [comment]
I'm looking at the code and it could be another AWS bug... they fixed a similar one a few weeks ago which was causing similar issues.  I definitely can't reproduce your issue at least.

Since it's been 9+ hours, it might just magically start working because your token has expired and `aws-sso` should in theory get another one.  But if that doesn't work, you can also flush the cached creds via `aws-sso flush -t all`

I _think_ that should fix it.  If not then try running with `-L trace` and report back.

**Comment by synfinatic** [comment]
Hey @pulberg, just checking in to see if the problem resolved itself or via `flush`?

**Comment by synfinatic** [comment]
Been 10 days.  If I don't hear back soon, i'll close the ticket assuming this has been resolved.

**Comment by jeremysimmons** [comment]
Had this issue too.
Adjusting the error message to include the instructions of pressing space instead of enter would be useful.

**Comment by synfinatic** [comment]
@jeremysimmons do you have some suggested verbiage which is clear and concise?

**Comment by Raymond-Cox** [comment]
Clearly still an issue, never encountered a cli which expected usage such as this. Had to learn how to use it through this issue.

**Comment by synfinatic** [comment]
@Raymond-Cox do you have some suggested verbiage which is clear and concise?  

alternatively some clear and verbose verbiage I can include in the docs?

**Comment by Raymond-Cox** [comment]
This comment from above was all I needed to see, maybe massage it into something more generic.
> Down Arrow to highlight AccountAlias and then hit <space> to select it by moving to the next word in the key/value pair.

**Comment by synfinatic** [comment]
thanks, that's helpful!
